import {
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    ArrowDown,
    ArrowUp,
    Bold,
    Check,
    ChevronDown,
    Cloud,
    CloudDownload,
    Copy,
    createIcons,
    Download,
    Eye,
    EyeOff,
    Folder,
    FolderSearch,
    Heading1,
    Heading2,
    Heading3,
    Image,
    Info,
    Italic,
    KeyRound,
    Library,
    Link,
    List,
    ListIndentDecrease,
    ListIndentIncrease,
    ListOrdered,
    MessageCirclePlus,
    MessageCircleWarning,
    Minus,
    PencilLine,
    Pilcrow,
    Play,
    Plug,
    Plus,
    Redo2,
    RefreshCw,
    RemoveFormatting,
    Replace,
    Search,
    Settings,
    ShieldCheck,
    Strikethrough,
    Square,
    Subscript,
    Superscript,
    Terminal,
    Trash2,
    Type,
    Underline,
    Undo2,
    WandSparkles,
    WrapText,
    X,
} from "lucide";

// Lucide intentionally excludes brand logos. Register the GitHub mark as a
// custom icon so templates can still use the same data-lucide="github" API.
const Github = [
    ["path", { d: "M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.28-.36 6.72-1.61 6.72-7A5.4 5.4 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S3.73 4.79 5.39 4.77A5.4 5.4 0 0 0 4 8.5c0 5.42 3.44 6.66 6.72 7A4.8 4.8 0 0 0 9 19v3" }],
    ["path", { d: "M9 18c-4.51 2-5-2-7-2" }],
];

const icons = {
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    ArrowDown,
    ArrowUp,
    Bold,
    Check,
    ChevronDown,
    Cloud,
    CloudDownload,
    Copy,
    Download,
    Eye,
    EyeOff,
    Folder,
    FolderSearch,
    Github,
    Heading1,
    Heading2,
    Heading3,
    Image,
    Info,
    Italic,
    KeyRound,
    Library,
    Link,
    List,
    ListIndentDecrease,
    ListIndentIncrease,
    ListOrdered,
    MessageCirclePlus,
    MessageCircleWarning,
    Minus,
    PencilLine,
    Pilcrow,
    Play,
    Plug,
    Plus,
    Redo2,
    RefreshCw,
    RemoveFormatting,
    Replace,
    Search,
    Settings,
    ShieldCheck,
    Strikethrough,
    Square,
    Subscript,
    Superscript,
    Terminal,
    Trash2,
    Type,
    Underline,
    Undo2,
    WandSparkles,
    WrapText,
    X,
};

export const renderIcons = (root = document) => {
    createIcons({
        icons,
        root,
        attrs: {
            "aria-hidden": "true",
            focusable: "false",
        },
    });
};
